RecetasMvc/Controllers/AccesoController.cs
using RecetaSpawn.Domain.BO;
using RecetaSpawn.Domain.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecetasMvc.Controllers
{
    public class AccesoController : Controller
    {
        TblUsuarioCTRL Total = new TblUsuarioCTRL();
        // GET: Acceso
        public ActionResult Login()
        {
            return View();
        }

        public int IniciarSesion()
        {
            string correo = Request.Form.Get("correo");
            string contraseña = Request.Form.Get("contraseña");

            TblUsuariosBO data = new TblUsuariosBO();

            data.Correo = correo;
            data.Contraseña = contraseña;

            try
            {
                int Y = 0;
                List<TblUsuariosBO> datos = Total.Validar(data);

                foreach (var des in datos)
                {
                    Session["ID"] = des.IDUsuario;
                    Session["Nombre"] = des.Nombre;
                    Session["Apellido"] = des.Apellido;
                    Session["Correo"] = des.Correo;
                    Session["Contraseña"] = des.Contraseña;
                    Session["Genero"] = des.Genero;
                    Session["Rol"] = des.Rol;

                }
                return 1;
            }
            catch
            {
                return 0;
            }

        }

        public ActionResult CerrarSesion()
        {
            Session["ID"] = null;
            Session["Nombre"] = null;
            Session["Apellido"] = null;
            Session["Correo"] = null;
            Session["Contraseña"] = null;
            Session["Genero"] = null;
            Session["Rol"] = null;
            return RedirectToAction("../Acceso/Login");
        }

        //
        public ActionResult RedirectRol()
        {
            if (Session["Rol"]!=null)
            {
                if (Session["Rol"].ToString() == "Administrador")
                {
                    return RedirectToAction("../Administrativo/AdminView");
                }
                else if (Session["Rol"].ToString() == "Cliente")
                {
                    return RedirectToAction("../Administrativo/ClientView");
                }
            }else
                return RedirectToAction("../Acceso/Login");
            return View();
        }
    }
}

RecetasMvc/Views/Shared/View.cshtml
@{
    ViewBag.Title = "View";
}

<h2>View</h2>

RecetasMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Freelancer - Start Bootstrap Theme</title>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/css/styles.css" rel="stylesheet" />
</head>
<body>

    @*Botones*@
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                @*<img src="~/Imagenes/logo1.png" />*@ Recetas Yucatecas
            </a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">

                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="~/Views/Admin/AdminView.cshtml">Agenda</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#Publicar">Publicar</a></li>
            
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" @Html.ActionLink("Iniciar Sesion", "Login", "Acceso")</a></li>

                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" @Html.ActionLink("Prueba", "AdminView", "Admin")</a></li>
                </ul>
            </div>
        </div>
    </nav>



    @*Imagenes Carrusel*@
    <header>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/Content/Imagenes/Brazo de reina.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/Imagenes/Panuchos.jpeg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/Imagenes/cochinita-pibil-olla-express.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/Imagenes/Salbutes.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="~/Imagenes/papadzules.jpg" class="d-block w-100" alt="...">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>

    </header>

    <!-- SECCION NOSOTROS  -->
    <section class="page-section bg-primary text-white mb-0" id="nosotros">
        <table id="nosotros" align="center" width="1000">
            <tbody>
                <tr>
                    <td align="center">
                        <h1 class="text-uppercase mb-4">¿Quienes Somos?</h1>
                    </td>
                </tr>
                <tr>
                    <td align="justify">
                        <h5>
                            <strong>La comida yucateca es de las más deliciosas y representativas de todo México</strong>
                            ,
                            tal vez comparable la jalisciense o la poblana en cuanto al arraigo en la cultura nacional.
                            Sin embargo, por la gran distancia que existe entre esta región y las ciudades del centro del
                            país, tiene un estilo muy particular que fusiona lo mejor de la tradición maya con las
                            incorporaciones hechas por los españoles tras la conquista.
                        </h5>

                        <h5>
                            Cuando estés de visita en Mérida o en otro destino del estado de Yucatán, notarás
                            que la gama de platillos es mucha y probablemente no sepas cuál elegir. Para que tengas
                            una idea de qué pedir en el restaurante que visites, aquí describimos algunos de los platillos
                            típicos de Yucatán que destacan por su sabor, su arraigo a la cultura local y su autenticidad.
                        </h5><br />
                    </td>
                </tr>
            </tbody>
        </table>
    </section>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- SECCION DE MEDIDAS BASICAS-->
    <section id="medidas" class="showcase">
        <div class="container-fluid p-0">
            <div class="row no-gutters">
                <!--IMAGEN UNO-->
                <img class="col-lg-6 order-lg-2 text-white showcase-img" src="~/Content/Imagenes/Puchero1.jpg" />
                <div padding="75" class="col-lg-6 order-lg-1 my-auto showcase-text">
                    <h2>Puchero</h2>
                    <h4 class="lead mb-0">
                        El puchero es otro de los tantos platillos pertenecientes a la gastronomía yucateca.
                        Este delicioso guiso es uno de los que gozan de mayor popularidad en Yucatán por su
                        auténtica combinación de sabores que deleitan las papilas gustativas.

                    </h4>
                </div>
            </div>
            <div class="row no-gutters">
                <!--IMAGEN DOS-->
                <img class="col-lg-6 text-white showcase-img" src="~/Content/Imagenes/Huevos-Motuleños.jpg" />
                <div padding="75" class="col-lg-6 my-auto showcase-text">
                    <h2>Huevos Motuleños</h2>
                    <h4 class="lead mb-0">
                        Se originan en Motul, en La Sin Rival, se dice que llegó a desayunar Felipe Carrillo Puerto,
                        con muchos invitados, entonces el dueño del local, el seño Siqueff  al no tener suficiente
                        para todos, modificó el platillo que tenía pensado agregándole tortilla con frijol, huevo estrellado,
                        jamón picado, salsa de tomate y chícharos. El platillo fue de tal agrado que se volvió parte del menú
                        y se dio a conocer como Huevos motuleños.
                    </h4>
                </div>
            </div>
            <div class="row no-gutters">
                <!--IMAGEN TRES-->
                <img class="col-lg-6 order-lg-2 text-white showcase-img" src="~/Content/Imagenes/poc-chuc.jpg" />
                <div padding="75" class="col-lg-6 order-lg-1 my-auto showcase-text">
                    <h2>Poc Chuc</h2>
                    <h4 class="lead mb-0">
                        Su origen es Maya, quienes usaban carne de jabalí, la salaban para conservarla
                        y la cocían sobre piedras calientes. Con el tiempo y a la llegada de los españoles
                        se sustituyó por carne de cerdo, y se le marinó en naranja agria y servirse con cebolla asada.
                    </h4>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section bg-primary text-white mb-0">
    </section>
    <section class="page-section bg-primary text-white mb-0">
    </section>
    <!-- Footer-->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">
                <!-- Footer Location-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Donde estamos?</h4>
                    <p class="lead mb-0">
                        calle falsa 123
                        <br />
                        Clark ken, osease superman
                    </p>
                </div>
                <!-- Footer Social Icons-->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Around the Web</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>

                </div>
                <!-- Footer About Text-->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About Freelancer</h4>
                    <p class="lead mb-0">
                        Freelance is a free to use, MIT licensed Bootstrap theme created by

                    </p>
                </div>
            </div>
        </div>

    </footer>

    <section>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright © Your Website 2020</small></div>
        </div>
    </section>






    <script src="~/Content/jquery/dist/jquery.min.js"></script>
    <script src="~/Content/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~" asp-append-version="true"></script>

    <script>
        var Root = "@Url.Content("~/")";
    </script>
    <script src="~/Content/Dialog/Dialog.js"></script>

    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="~/Content/js/scripts.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

RecetasMvc/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}
<DOCTYPE html>

    <html lang="en">

    <head>
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="~/Content/CssAdmin/assets/img/apple-icon.png">
        <link rel="icon" type="image/png" href="~/Content/CssAdmin/assets/img/favicon.png">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>
            Recetas Yucatan :)
        </title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
        <!-- CSS Files -->
        <link href="~/Content/CssAdmin/assets/css/material-dashboard.css" rel="stylesheet" />

        <!-- CSS Just for demo purpose, don't include it in your project -->
        <link href="~/Content/CssAdmin/assets/demo/demo.css" rel="stylesheet" />
        <script src="~/Content/jquery/dist/jquery.js"></script>
        <link href="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" />
        <link href="~/Content/Dialog/Dialog-ie.css" rel="stylesheet" />
        <link href="~/Content/Dialog/Dialog.css" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    </head>

    <body class="dark-edition">
        <div class="wrapper ">
            <div class="sidebar" data-color="purple" data-background-color="black" data-image="../assets/img/sidebar-2.jpg">
                <!--
                Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

                Tip 2: you can also add an image using data-image tag
            -->
                <div class="logo">
                    <a href="~/Views/Shared/_Layout.cshtml" class="simple-text logo-normal">
                        Recetas Yucatan
                    </a>
                </div>
                <div class="sidebar-wrapper">
                    <ul class="nav">
                        @{
                            if ((Session["Rol"]).ToString() == "Administrador")
                            {

                                <li class="nav-item active  ">
                                    <a class="nav-link" href="@Url.Content("~/Receta/Ver")">
                                        <i class="material-icons">dashboard</i>
                                        <p>R E C E T A</p>
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="@Url.Content("~/Usuarios/Ver")">
                                        <i class="material-icons">persone</i>
                                        <p>U S U A R I O</p>
                                    </a>
                                </li>
                            }
                            else if ((Session["Rol"]).ToString() == "Cliente")
                            {
                                <li class="nav-item ">
                                    <a class="nav-link" href="@Url.Content("~/Ver/MisRecetas")">
                                        <i class="material-icons">content_paste</i>
                                        <p>Mis Recetas</p>
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="@Url.Content("~/Receta/Agregar")">
                                        <i class="material-icons">library_books</i>
                                        <p>Nueva Receta</p>
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="@Url.Content("~/Ver/Publicaciones")">
                                        <i class="material-icons">bubble_chart</i>
                                        <p>Publicacion</p>
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="./map.html">
                                        <i class="material-icons">location_ons</i>
                                        <p>Maps</p>
                                    </a>
                                </li>
                            }
                        }


                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Content("~/Acceso/CerrarSesion")">
                                @*<icon*@
                                <i class="material-icons">Cerrar sesion</i>
                                <p>Cerrar Sesion</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="main-panel">
                <!-- Navbar -->
                <nav style="position:static" class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top " id="navigation-example">
                    <div class="container-fluid">
                        <div class="navbar-wrapper">
                            <a class="navbar-brand" href="javascript:void(0)">Panel Administrativo<a>
                        </div>
                        
                    </div>
                </nav>
                <div style="padding:50px">
                    @RenderBody()
                </div>
            </div>

                <footer class="footer">
                    <div class="container-fluid">
                        <nav class="float-left">
                            <ul>
                                <li>
                                    <a href="https://www.creative-tim.com">
                                        Creative Tim
                                    </a>
                                </li>
                                <li>
                                    <a href="https://creative-tim.com/presentation">
                                        About Us
                                    </a>
                                </li>
                                <li>
                                    <a href="http://blog.creative-tim.com">
                                        Blog
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.creative-tim.com/license">
                                        Licenses
                                    </a>
                                </li>
                            </ul>
                        </nav>
                        <div class="copyright float-right" id="date">
                            , made with <i class="material-icons">favorite</i> by
                            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
                        </div>
                    </div>
                </footer>
                <script>
                    const x = new Date().getFullYear();
                    let date = document.getElementById('date');
                    date.innerHTML = '&copy; ' + x + date.innerHTML;
                </script>

            </div>


        <!--   Core JS Files   -->
        <script src="~/Content/CssAdmin/assets/js/core/jquery.min.js"></script>
        <script src="~/Content/CssAdmin/assets/js/core/popper.min.js"></script>
        <script src="~/Content/CssAdmin/assets/js/core/bootstrap-material-design.min.js"></script>
        <script src="https://unpkg.com/default-passive-events"></script>
        <script src="~/Content/CssAdmin/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
        <!-- Place this tag in your head or just before your close body tag. -->
        <script async defer src="https://buttons.github.io/buttons.js"></script>
        <!--  Google Maps Plugin    -->
        <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
        <!-- Chartist JS -->
        <script src="~/Content/CssAdmin/assets/js/plugins/chartist.min.js"></script>
        <!--  Notifications Plugin    -->
        <script src="~/Content/CssAdmin/assets/js/plugins/bootstrap-notify.js"></script>
        <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
        <script src="~/Content/CssAdmin/assets/js/material-dashboard.js"></script>
        <!-- Material Dashboard DEMO methods, don't include it in your project! -->
        <script src="~/Content/CssAdmin/assets/demo/demo.js"></script>
        <!--AVER SI ESTO NO AFECTA.... x.x-->

        <script>
            var Root = "@Url.Content("~/")";
        </script>

        <script src="~/Content/Dialog/Dialog.js"></script>
    </body>

</html>